[package]
name = "project-euler-0050"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.8.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
