[package]
name = "project-euler-026"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4.4"
num-traits = "0.2.17"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
