[package]
name = "project-euler-002"
version = "0.1.0"
edition = "2021"

[dependencies]
bencher = "0.1.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
